export const MUTATIONS = {
  app: {
    updateLoading: "updateLoading",
  },
  auth: {
    updateMobile: "updateMobile",
    updatePassword: "updatePassword",
    toggleIsSubmitting: "toggleIsSubmitting",
    updateMobileRegister: "updateMobileRegister",
    updatePasswordRegister: "updatePasswordRegister",
    updateRefRegister: "updateRefRegister",
    setCurrentUser: "setCurrentUser",
    updateMobileForgetPassword: "updateMobileForgetPassword",
    formSubmitForgetPasswordUser: "formSubmitForgetPasswordUser",
    updateCodeConfirm: "updateCodeConfirm",
    createNewPassword: "createNewPassword",
    createNewPasswordConfirm: "createNewPasswordConfirm",
    postForgetNewPassword: "postForgetNewPassword",
    formSubmitCreateNewPasswordAndConfirm:
      "formSubmitCreateNewPasswordAndConfirm",
    formSubmitCodeConfirm: "formSubmitCodeConfirm",
    forgetPasswordUser: "forgetPasswordUser",
  },
  panel: {
    showSidebar: "showSidebar",
    sidebarSmall: "sidebarSmall",
    showValueWalletUser: "showValueWalletUser",
    showValueDiscountUser: "showValueDiscountUser",
    showValueCreditUser: "showValueCreditUser",
    showValueOrganUser: "showValueOrganUser",
    getHistory: "getHistory",
    setValueAmount: "setValueAmount",
    setChargeWallet: "setChargeWallet",
    getInformation: "getInformation",
    setMobileCharge: "setMobileCharge",
    setAmountCharge: "setAmountCharge",
    postDataToBuyCharge: "postDataToBuyCharge",
    setMobileCard: "setMobileCard",
    setCardNumber: "setCardNumber",
    postDestinationinfo: "postDestinationinfo",
    getListInternetPackageAsServer: "getListInternetPackageAsServer",
    setOperatorCharge: "setOperatorCharge",
    setRechargeCodeHamrah: "setRechargeCodeHamrah",
    setItemOperatorBill: "setItemOperatorBill",
    setIdForListItemOperatorBill: "setIdForListItemOperatorBill",
    postDataPaymentBill: "postDataPaymentBill",
    postCardNumberDestinationinfo: "postCardNumberDestinationinfo",
    getSettingProfile: "getSettingProfile",
    updatePasswordSettingProfile: "updatePasswordSettingProfile",
    updateNewPasswordSettingProfile: "updateNewPasswordSettingProfile",
    postDataForgetPasswordSettingProfile:
      "postDataForgetPasswordSettingProfile",
    getDataList: "getDataList",
    getDataAcoountBanks: "getDataAcoountBanks",
    updateConfirmExit: "updateConfirmExit",
    updateOffShowConfirmExit: "updateOffShowConfirmExit",
    updateBankCardNumber: "updateBankCardNumber",
    updateSetActiveFullname: "updateSetActiveFullname",
    getDataCards: "getDataCards",
  },
};
